name: Frontend Lint

on:
  push:
  pull_request:

jobs:
  build:
    name: Check Application
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: yarn install

    - name: Install CI checks
      run: yarn install --frozen-lockfile

    - name: Check Types
      run: yarn run typecheck

    - name: Lint with Biome
      run: yarn run check:code

    - name: Lint Styles
      run: yarn run lint:code

    - name: Lint Code
      run: yarn run lint:styles

    - name: Test Production Build
      run: yarn run build