name: Frontend Docker [Development]

on:
  push:
  pull_request:

jobs:
  build:
    name: Build Docker Container
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Make Dev Application in Docker
      run: make production
    
    - name: Check Docker Container
      run: make check